excluded:
    - Pods
    - Resources
    - Swift_Packages

disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace

opt_in_rules:
        - balanced_xctest_lifecycle
        - closure_end_indentation
        - closure_spacing
        - closure_parameter_position
        - colon
        - comma
        - comment_spacing
        - comma_inheritance
        - contains_over_filter_count
        - contains_over_filter_is_empty
        - contains_over_first_not_nil
        - contains_over_range_nil_comparison
        - cyclomatic_complexity
        - empty_collection_literal
        - empty_xctest_method
        - fatal_error_message
        - file_name
        - file_name_no_space
        - first_where
        - flatmap_over_map_reduce
        - force_unwrapping
        - identical_operands
        - implicitly_unwrapped_optional
        - last_where
        - literal_expression_end_indentation
        - lower_acl_than_parent
        - modifier_order
        - multiline_arguments
        - multiline_parameters
        - no_extension_access_modifier
        - operator_usage_whitespace
        - optional_enum_case_matching
        - prefer_zero_over_explicit_init
        - private_subject
        - redundant_nil_coalescing
        - return_value_from_void_function
        - sorted_first_last
        - sorted_imports
        - toggle_bool
        - unowned_variable_capture
        - vertical_whitespace_between_cases
        - vertical_whitespace_closing_braces
        - vertical_whitespace_opening_braces
        - yoda_condition

function_body_length:
   warning: 200
   error: 250
file_length:
   warning: 500
   error: 1000
   ignore_comment_only_lines: true
line_length:
   warning: 150
   error: 300
nesting:
   type_level:
     warning: 3
type_body_length:
   warning: 500
   error: 1000
function_parameter_count:
   warning: 20
   error: 30
cyclomatic_complexity:
    warning: 26
    error: 26
line_length: 100
function_body_length: 300
function_parameter_count: 15
file_length: 500
type_body_length: 300
large_tuple: 3


force_cast:
     severity: warning
force_try:
  severity: warning
force_try:
  severity: warning
no_extension_access_modifier:
  severity: warning
shorthand_operator:
  severity: warning
duplicate_enum_cases:
  severity: warning
dynamic_inline:
  severity: warning
generic_type_name:
  severity: warning

cyclomatic_complexity:
    warning: 10
    error: 15
    ignores_case_statements: true

identifier_name:
    min_length: 
      warning: 1
    max_length: 
      warning: 50
    allowed_symbols: ["_"]
    excluded:
    - id

type_name:
    min_length:
      warning: 1
    max_length:
      warning: 50


analyzer_rules:
- unused_import
- unused_declaration
